### ISSUE TITLE
Proxy file

### ISSUE THREAD

**Issue by Huzaifa1122334** [AJTimePyro/Crunchyroll-Account-Checker#12]
Sir if i not want to add proxy file what i write in that option?i have try to leave it empty by pressing "enter" without writing anything but it shows error then.

**Comment by AJTimePyro** [comment]
Send the errors

**Comment by Huzaifa1122334** [comment]
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/Crunchyroll-Account-Checker/main.py", line 45, in <module>
    main()
  File "/data/data/com.termux/files/home/Crunchyroll-Account-Checker/main.py", line 38, in main
    src.checker.CrunchyrollChecker.create(filename, proxy_filename)
  File "/data/data/com.termux/files/home/Crunchyroll-Account-Checker/src/checker.py", line 53, in create
    self = CrunchyrollChecker(filename, proxy_filename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/Crunchyroll-Account-Checker/src/checker.py", line 44, in __init__
    self.proxyObj = proxy.Proxy(proxy_filename)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/Crunchyroll-Account-Checker/src/proxy.py", line 28, in __init__
    self.getProxies()
  File "/data/data/com.termux/files/home/Crunchyroll-Account-Checker/src/proxy.py", line 33, in getProxies
    self.writeToFile(request.response)
  File "/data/data/com.termux/files/home/Crunchyroll-Account-Checker/src/proxy.py", line 40, in writeToFile
    file.write(res)
TypeError: write() argument must be str, not dict

**Comment by Huzaifa1122334** [comment]
When i put or not the proxy file the same error is showing.

**Comment by AJTimePyro** [comment]
Try the latest commit, which now includes option to use or not to use proxy, and also resolved the given error

**Comment by Huzaifa1122334** [comment]
Working bro
