### ISSUE TITLE
cant run it

### ISSUE THREAD

**Issue by Downlaofy123** [AJTimePyro/Crunchyroll-Account-Checker#14]
Traceback (most recent call last):
  File "C:\Users\hdibe\OneDrive\Desktop\Crunchyroll-Account-Checker-master\main.py", line 55, in <module>
    main()
  File "C:\Users\hdibe\OneDrive\Desktop\Crunchyroll-Account-Checker-master\main.py", line 48, in main
    src.checker.CrunchyrollChecker.create(filename, proxy_filename, proxyEnable)
  File "C:\Users\hdibe\OneDrive\Desktop\Crunchyroll-Account-Checker-master\src\checker.py", line 57, in create
    self._checker()
  File "C:\Users\hdibe\OneDrive\Desktop\Crunchyroll-Account-Checker-master\src\checker.py", line 61, in _checker
    for line in file.readlines():
                ^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 1939: character maps to <undefined>

**Comment by AJTimePyro** [comment]
Try and tell, if it's work or not
