### ISSUE TITLE
ValueError:

### ISSUE THREAD

**Issue by Downwrghty** [AJTimePyro/Crunchyroll-Account-Checker#4]
[ValueError](valueerror: too many values to unpack (expected 2) fix)

any fix?

**Comment by AJTimePyro** [comment]
Umm provide me more details, as this is insufficient information to fix the issue.

**Comment by Downwrghty** [comment]
sure, here:
Traceback (most recent call last):
  File "C:\Users\User\Desktop\Crunchyroll-Account-Checkemaster\main.py", line 33, in <module>
    main()
  File "C:\Users\User\Desktop\Crunchyroll-Account-Checkemaster\main.py", line 26, in main
    src.checker.CrunchyrollChecker.create(filename)
  File "C:\Users\User\Desktop\Crunchyroll-Account-Checkemaster\src\checker.py", line 41, in create
    self._checker()
  File "C:\Users\User\Desktop\Crunchyroll-Account-Checkemaster\src\checker.py", line 46, in _checker
    loginDetail = self._filterEmailPass(line)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\Crunchyroll-Account-Checkemaster\src\checker.py", line 122, in _filterEmailPass
    self.email, self.password = loginDetail[0].split(':')
    ^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: too many values to unpack (expected 2)
